"use client";
/* eslint-disable @next/next/no-img-element */

import type { User } from "firebase/auth";
import { Check, CircleCheck, Disc3, Heart, LoaderCircle, Music2, Play, Plus, Sparkles, Trash2, Utensils, MapPin, Film, ListTodo, Trophy } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { addDoc, arrayUnion, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from "@/lib/database";
import { LoginScreen } from "@/components/auth/login-screen";
import { BottomNav } from "@/components/layout/bottom-nav";
import { PairingScreen } from "@/components/pairing/pairing-screen";
import { useAuth } from "@/components/providers/auth-provider";
import { useCoupleSpace } from "@/components/providers/couple-provider";
import { db } from "@/lib/firebase";
import { useMusicPlayer, type MusicTrack } from "@/components/providers/music-player-provider";
import type { CoupleChallengeDocument, MusicHistoryDocument, WishItemDocument } from "@/types/firestore";

type Feature = "musiclog" | "wishlist" | "challenges";
type WithId<T> = T & { id: string };

export function PhaseThreeScreen({ feature }: { feature: Feature }) {
  const { user } = useAuth();
  const { couple, profile, loading } = useCoupleSpace();
  if (!user) return <LoginScreen />;
  if (loading) return <main className="grid min-h-dvh place-items-center"><Heart className="size-9 animate-pulse fill-blush text-blush" /></main>;
  if (!couple) return <PairingScreen user={user} />;
  const authorName = profile?.nickname || profile?.displayName || user.displayName || "Người thương";
  const headings = { musiclog: <><Music2 className="size-7 text-[#d17485]" />Nhật ký nghe nhạc</>, wishlist: <><ListTodo className="size-7 text-[#d17485]" />Danh sách mong muốn</>, challenges: <><Trophy className="size-7 text-[#d17485]" />Thử thách đôi</> };
  return <main className="min-h-dvh px-4 pb-32 pt-7 sm:px-6"><section className="app-frame"><header><p className="font-handwritten text-xl text-[#a56f78]">Cùng nhau hoàn thành</p><h1 className="flex items-center gap-2 font-display text-3xl font-extrabold">{headings[feature]}</h1></header><div className="mt-5 grid grid-cols-3 gap-2 rounded-2xl bg-white/65 p-2 shadow-soft"><Link className={`rounded-xl px-2 py-2 text-center text-xs font-bold ${feature === "musiclog" ? "bg-[#d96578] text-white" : "text-[#806e65]"}`} href="/music-history">Nhật ký nhạc</Link><Link className={`rounded-xl px-2 py-2 text-center text-xs font-bold ${feature === "wishlist" ? "bg-[#d96578] text-white" : "text-[#806e65]"}`} href="/wishlist">Mong muốn</Link><Link className={`rounded-xl px-2 py-2 text-center text-xs font-bold ${feature === "challenges" ? "bg-[#d96578] text-white" : "text-[#806e65]"}`} href="/challenges">Thử thách</Link></div>{feature === "musiclog" ? <MusicLog coupleId={couple.id} /> : feature === "wishlist" ? <Wishlist coupleId={couple.id} user={user} authorName={authorName} /> : <Challenges coupleId={couple.id} user={user} authorName={authorName} />}</section><BottomNav /></main>;
}

function MusicLog({ coupleId }: { coupleId: string }) {
  const [items, setItems] = useState<Array<WithId<MusicHistoryDocument>>>([]); const [error, setError] = useState(""); const { playTrack } = useMusicPlayer();
  useEffect(() => onSnapshot(query(collection(db, "couples", coupleId, "musicHistory"), orderBy("playedAt", "desc")), (snapshot) => { setItems(snapshot.docs.slice(0, 100).map((item) => ({ id: item.id, ...item.data() } as WithId<MusicHistoryDocument>))); setError(""); }, (caught) => setError(caught.message)), [coupleId]);
  function replay(item: MusicHistoryDocument) { const track: MusicTrack = { id: item.trackId, source: item.source, title: item.title, artist: item.artist, duration: "", thumbnail: item.thumbnail, url: item.url }; playTrack(track, [track]); }
  return <div className="mt-6">{error && <p className="rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="space-y-3">{items.map((item) => <article className="soft-card flex items-center gap-3 p-3" key={item.id}><span className="grid size-14 shrink-0 place-items-center overflow-hidden rounded-2xl bg-blush/30">{item.thumbnail ? <img src={item.thumbnail} alt="" className="size-full object-cover" /> : <Disc3 className="size-6" />}</span><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{item.title}</h2><p className="truncate text-xs text-[#8b756a]">{item.artist} · nghe bởi {item.playedByName}</p><p className="text-[10px] text-[#aa7a83]">{item.playedAt?.toDate ? item.playedAt.toDate().toLocaleString("vi-VN") : "Vừa nghe"}</p></div><button className="grid size-10 shrink-0 place-items-center rounded-full bg-blush/35" type="button" onClick={() => replay(item)} aria-label="Phát lại"><Play className="size-4 fill-current" /></button></article>)}{items.length === 0 && <p className="soft-card p-8 text-center text-sm text-[#8b756a]">Khi một trong hai người phát nhạc, bài hát sẽ xuất hiện tại đây.</p>}</div></div>;
}

const wishIcons = { food: Utensils, place: MapPin, movie: Film, activity: Sparkles, other: Heart };

function Wishlist({ coupleId, user, authorName }: { coupleId: string; user: User; authorName: string }) {
  const [items, setItems] = useState<Array<WithId<WishItemDocument>>>([]); const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [category, setCategory] = useState<WishItemDocument["category"]>("food"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => onSnapshot(query(collection(db, "couples", coupleId, "wishItems"), orderBy("createdAt", "desc")), (snapshot) => { setItems(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as WithId<WishItemDocument>))); setError(""); }, (caught) => setError(caught.message)), [coupleId]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim()) return; setBusy(true); try { await addDoc(collection(db, "couples", coupleId, "wishItems"), { title: title.trim(), note: note.trim(), category, status: "open", createdAt: serverTimestamp(), creatorId: user.uid, creatorName: authorName }); setTitle(""); setNote(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Chưa thể thêm mong muốn."); } finally { setBusy(false); } }
  async function toggle(item: WithId<WishItemDocument>) { await updateDoc(doc(db, "couples", coupleId, "wishItems", item.id), { status: item.status === "done" ? "open" : "done", completedAt: item.status === "done" ? null : serverTimestamp() }); }
  return <div className="mt-6"><form className="soft-card grid gap-3 p-4 sm:grid-cols-2" onSubmit={submit}><input className="input-field sm:col-span-2" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Hai mình muốn làm gì?" /><select className="input-field" value={category} onChange={(e) => setCategory(e.target.value as WishItemDocument["category"])}><option value="food">Món muốn ăn</option><option value="place">Nơi muốn đi</option><option value="movie">Phim muốn xem</option><option value="activity">Hoạt động</option><option value="other">Điều khác</option></select><input className="input-field" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Ghi chú (không bắt buộc)" /><button className="primary-button sm:col-span-2" disabled={busy}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Plus className="size-4" />}Thêm vào danh sách</button></form>{error && <p className="mt-3 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 space-y-3">{items.map((item) => { const Icon = wishIcons[item.category] || Heart; return <article className={`soft-card flex items-center gap-3 p-3 ${item.status === "done" ? "opacity-65" : ""}`} key={item.id}><button type="button" onClick={() => void toggle(item)} className={`grid size-11 shrink-0 place-items-center rounded-2xl ${item.status === "done" ? "bg-emerald-100 text-emerald-700" : "bg-blush/30 text-[#c66f80]"}`} aria-label="Đổi trạng thái">{item.status === "done" ? <CircleCheck className="size-5" /> : <Icon className="size-5" />}</button><div className="min-w-0 flex-1"><h2 className={`font-bold ${item.status === "done" ? "line-through" : ""}`}>{item.title}</h2><p className="text-xs text-[#8b756a]">{item.note || `Thêm bởi ${item.creatorName}`}</p></div>{item.creatorId === user.uid && <button type="button" onClick={() => void deleteDoc(doc(db, "couples", coupleId, "wishItems", item.id))} aria-label="Xóa"><Trash2 className="size-4 text-[#b88]" /></button>}</article>; })}{items.length === 0 && <p className="soft-card p-8 text-center text-sm text-[#8b756a]">Danh sách đang trống. Thêm một điều hai bạn muốn cùng làm nhé.</p>}</div></div>;
}

function Challenges({ coupleId, user, authorName }: { coupleId: string; user: User; authorName: string }) {
  const [items, setItems] = useState<Array<WithId<CoupleChallengeDocument>>>([]); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [targetDays, setTargetDays] = useState(7); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => onSnapshot(query(collection(db, "couples", coupleId, "coupleChallenges"), orderBy("createdAt", "desc")), (snapshot) => { setItems(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as WithId<CoupleChallengeDocument>))); setError(""); }, (caught) => setError(caught.message)), [coupleId]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim()) return; setBusy(true); try { await addDoc(collection(db, "couples", coupleId, "coupleChallenges"), { title: title.trim(), description: description.trim(), targetDays: Math.max(1, Math.min(365, targetDays)), checkInDates: [], status: "active", createdAt: serverTimestamp(), creatorId: user.uid, creatorName: authorName }); setTitle(""); setDescription(""); setTargetDays(7); } catch (caught) { setError(caught instanceof Error ? caught.message : "Chưa thể tạo thử thách."); } finally { setBusy(false); } }
  async function checkIn(item: WithId<CoupleChallengeDocument>) { const today = new Date().toISOString().slice(0, 10); if (item.checkInDates?.includes(`${today}:${user.uid}`)) return; const nextCount = (item.checkInDates?.length || 0) + 1; await updateDoc(doc(db, "couples", coupleId, "coupleChallenges", item.id), { checkInDates: arrayUnion(`${today}:${user.uid}`), status: nextCount >= item.targetDays * 2 ? "completed" : item.status }); }
  return <div className="mt-6"><form className="soft-card grid gap-3 p-4 sm:grid-cols-2" onSubmit={submit}><input className="input-field" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Tên thử thách" /><label className="input-field flex items-center gap-2"><span className="text-sm">Số ngày</span><input className="min-w-0 flex-1 bg-transparent text-right outline-none" type="number" min="1" max="365" value={targetDays} onChange={(e) => setTargetDays(Number(e.target.value))} /></label><textarea className="input-field min-h-20 sm:col-span-2" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Ví dụ: chụp một ảnh mỗi ngày, uống đủ nước..." /><button className="primary-button sm:col-span-2" disabled={busy}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Plus className="size-4" />}Bắt đầu thử thách</button></form>{error && <p className="mt-3 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 space-y-3">{items.map((item) => { const today = new Date().toISOString().slice(0, 10); const checked = item.checkInDates?.includes(`${today}:${user.uid}`); const progress = Math.min(100, Math.round(((item.checkInDates?.length || 0) / (item.targetDays * 2)) * 100)); return <article className="soft-card p-4" key={item.id}><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-amber-100 text-amber-700"><Trophy className="size-5" /></span><div className="min-w-0 flex-1"><h2 className="font-bold">{item.title}</h2><p className="text-xs text-[#8b756a]">{item.description || `${item.targetDays} ngày cùng nhau`}</p></div>{item.creatorId === user.uid && <button type="button" onClick={() => void deleteDoc(doc(db, "couples", coupleId, "coupleChallenges", item.id))}><Trash2 className="size-4 text-[#b88]" /></button>}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-blush/20"><div className="h-full rounded-full bg-[#d96578] transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-2 flex items-center justify-between text-xs"><span>{item.checkInDates?.length || 0}/{item.targetDays * 2} lượt · {progress}%</span><button type="button" disabled={checked || item.status === "completed"} onClick={() => void checkIn(item)} className="secondary-button min-h-9 px-3">{checked || item.status === "completed" ? <Check className="size-4" /> : null}{item.status === "completed" ? "Hoàn thành" : checked ? "Đã check-in hôm nay" : "Check-in"}</button></div></article>; })}{items.length === 0 && <p className="soft-card p-8 text-center text-sm text-[#8b756a]">Chưa có thử thách nào. Hai bạn bắt đầu một mục tiêu nhỏ nhé.</p>}</div></div>;
}
