"use client";
/* eslint-disable @next/next/no-img-element */

import { collection, getDocs, limit, orderBy, query } from "@/lib/database";
import { Download, FileText, Fingerprint, Heart, KeyRound, LoaderCircle, Lock, Save, ShieldCheck, Smartphone } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { LoginScreen } from "@/components/auth/login-screen";
import { BottomNav } from "@/components/layout/bottom-nav";
import { PairingScreen } from "@/components/pairing/pairing-screen";
import { useAuth } from "@/components/providers/auth-provider";
import { useCoupleSpace } from "@/components/providers/couple-provider";
import { bytesToBase64Url, getLockConfig, hashPin, saveLockConfig } from "@/lib/app-lock";
import { db } from "@/lib/firebase";
import { collectCoupleData } from "@/lib/couple-backup";
import type { PhotoDocument } from "@/types/firestore";

type Feature = "widget" | "data" | "security";
export function PhaseFourScreen({ feature }: { feature: Feature }) {
  const { user } = useAuth(); const { couple, profile, partner, loading } = useCoupleSpace();
  if (!user) return <LoginScreen />;
  if (loading) return <main className="grid min-h-dvh place-items-center"><Heart className="size-9 animate-pulse fill-blush text-blush" /></main>;
  if (!couple) return <PairingScreen user={user} />;
  const titles = { widget: "Widget đếm ngày", data: "Xuất & sao lưu", security: "Khóa riêng" };
  return <main className="min-h-dvh px-4 pb-32 pt-7 sm:px-6"><section className="app-frame"><header><p className="font-handwritten text-xl text-[#a56f78]">Bảo vệ những điều quý giá</p><h1 className="font-display text-3xl font-extrabold">{titles[feature]}</h1></header><div className="mt-5 grid grid-cols-3 gap-2 rounded-2xl bg-white/65 p-2 shadow-soft">{(["widget", "data", "security"] as Feature[]).map((key) => <Link key={key} href={`/${key}`} className={`rounded-xl px-2 py-2 text-center text-xs font-bold ${feature === key ? "bg-[#d96578] text-white" : "text-[#806e65]"}`}>{titles[key]}</Link>)}</div>{feature === "widget" && <WidgetPanel coupleId={couple.id} startDate={couple.startDate?.toDate()} names={`${profile?.nickname || profile?.displayName || "Bạn"} & ${partner?.nickname || partner?.displayName || "Người thương"}`} />}{feature === "data" && <DataPanel coupleId={couple.id} />}{feature === "security" && <SecurityPanel userId={user.uid} userName={profile?.nickname || profile?.displayName || user.displayName || "Love Days"} />}</section><BottomNav /></main>;
}

function WidgetPanel({ coupleId, startDate, names }: { coupleId: string; startDate?: Date; names: string }) {
  const [photo, setPhoto] = useState<PhotoDocument | null>(null);
  useEffect(() => { void getDocs(query(collection(db, "couples", coupleId, "photos"), orderBy("createdAt", "desc"), limit(1))).then((snapshot) => setPhoto(snapshot.docs[0]?.data() as PhotoDocument || null)); }, [coupleId]);
  const days = useMemo(() => startDate ? Math.max(1, Math.floor((Date.now() - startDate.getTime()) / 86400000) + 1) : 0, [startDate]);
  return <div className="mt-6"><section className="mx-auto aspect-[4/3] max-w-sm overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#f7b4bf] to-[#f8d7c2] p-4 shadow-soft"><div className="relative flex size-full flex-col justify-between overflow-hidden rounded-[1.5rem] bg-white/65 p-5">{photo && <img src={photo.imageUrl} alt="Ảnh chung" className="absolute inset-0 size-full object-cover opacity-25" />}<p className="relative font-display font-bold">Love Days ♥</p><div className="relative text-center"><p className="text-6xl font-extrabold text-[#c95f75]">{days}</p><p className="font-handwritten text-2xl">ngày bên nhau</p></div><p className="relative truncate text-center text-sm font-bold">{names}</p></div></section><section className="soft-card mt-5 p-5"><h2 className="flex items-center gap-2 font-bold"><Smartphone className="size-5" />Đưa ra màn hình chính</h2><p className="mt-2 text-sm text-[#806e65]">iPhone: mở menu Chia sẻ trong Safari → Thêm vào Màn hình chính. Android: mở menu trình duyệt → Cài đặt ứng dụng. Biểu tượng Love Days sẽ mở thẳng bộ đếm ngày.</p><p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">PWA trên iPhone/Android chưa hỗ trợ widget động giống ứng dụng native trên mọi thiết bị. Màn hình này là widget nhanh hoạt động ổn định khi mở từ biểu tượng.</p></section></div>;
}

function DataPanel({ coupleId }: { coupleId: string }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { setBusy(true); setError(""); try { return await collectCoupleData(coupleId); } catch (caught) { setError(caught instanceof Error ? caught.message : "Chưa thể đọc dữ liệu."); throw caught; } finally { setBusy(false); } }
  async function downloadJson() { try { const data = await load(); const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `love-days-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); setMessage("Đã tạo bản xuất dữ liệu."); } catch {} }
  async function printPdf() { try { const data = await load(); const printable = window.open("", "_blank"); if (!printable) throw new Error("Trình duyệt đang chặn cửa sổ in."); const sections = Object.entries(data.data).map(([name, values]) => `<h2>${name} (${values.length})</h2><pre>${escapeHtml(JSON.stringify(values, null, 2))}</pre>`).join(""); printable.document.write(`<title>Love Days backup</title><style>body{font:14px sans-serif;padding:24px}pre{white-space:pre-wrap;background:#faf5f2;padding:12px}h2{page-break-after:avoid}</style><h1>Love Days — ${new Date().toLocaleDateString("vi-VN")}</h1>${sections}`); printable.document.close(); printable.print(); setMessage("Chọn “Lưu thành PDF” trong cửa sổ in."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Chưa thể tạo PDF."); } }
  return <div className="mt-6"><section className="soft-card p-5"><h2 className="font-display text-xl font-bold">Mang kỷ niệm theo bạn</h2><p className="mt-1 text-sm text-[#806e65]">Bản xuất gồm nội dung, ngày tháng và đường dẫn ảnh/video. File media gốc vẫn nằm trên Cloudinary.</p><button className="primary-button mt-5 w-full" disabled={busy} onClick={downloadJson}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Download className="size-4" />}Tải bản sao JSON</button><button className="secondary-button mt-3 w-full" disabled={busy} onClick={printPdf}><FileText className="size-4" />In hoặc lưu PDF</button></section><section className="soft-card mt-4 p-5"><h2 className="flex items-center gap-2 font-bold"><Save className="size-5" />Sao lưu tự động trên thiết bị</h2><p className="mt-2 text-sm text-[#806e65]">Ứng dụng tự cập nhật một bản sao cục bộ mỗi 24 giờ khi bạn mở app. Bản này giúp phục hồi nội dung văn bản nếu Apps Script tạm thời gặp lỗi.</p><p className="mt-3 text-xs font-semibold text-[#a56f78]">Lần gần nhất: {localStorage.getItem(`love-days-backup-time:${coupleId}`) ? new Date(localStorage.getItem(`love-days-backup-time:${coupleId}`)!).toLocaleString("vi-VN") : "Chưa có"}</p></section>{message && <p className="mt-3 rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error && <p className="mt-3 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div>;
}

function escapeHtml(value: string) { return value.replace(/[&<>]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[character] || character); }

function SecurityPanel({ userId, userName }: { userId: string; userName: string }) {
  const [config, setConfig] = useState(getLockConfig); const [pin, setPin] = useState(""); const [confirmPin, setConfirmPin] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function savePin(event: FormEvent) { event.preventDefault(); if (!/^\d{4,6}$/.test(pin)) return setError("PIN cần có từ 4 đến 6 chữ số."); if (pin !== confirmPin) return setError("Hai mã PIN chưa khớp."); setBusy(true); const next = { ...config, enabled: true, pinHash: await hashPin(pin) }; saveLockConfig(next); setConfig(next); setPin(""); setConfirmPin(""); setBusy(false); setMessage("Đã bật khóa PIN."); setError(""); }
  async function enableBiometric() { if (!window.PublicKeyCredential || !navigator.credentials) return setError("Thiết bị này chưa hỗ trợ Face ID/vân tay cho website."); setBusy(true); setError(""); try { const credential = await navigator.credentials.create({ publicKey: { challenge: crypto.getRandomValues(new Uint8Array(32)), rp: { name: "Love Days" }, user: { id: new TextEncoder().encode(userId), name: userName, displayName: userName }, pubKeyCredParams: [{ alg: -7, type: "public-key" }, { alg: -257, type: "public-key" }], authenticatorSelection: { authenticatorAttachment: "platform", residentKey: "preferred", userVerification: "required" }, timeout: 60000, attestation: "none" } }) as PublicKeyCredential | null; if (!credential) throw new Error("Không tạo được khóa."); const next = { ...config, enabled: true, credentialId: bytesToBase64Url(new Uint8Array(credential.rawId)) }; saveLockConfig(next); setConfig(next); setMessage("Đã bật Face ID/vân tay."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Không thể bật sinh trắc học."); } finally { setBusy(false); } }
  function disable() { const next = { enabled: false }; saveLockConfig(next); setConfig(next); setMessage("Đã tắt khóa riêng trên thiết bị này."); }
  return <div className="mt-6"><section className="soft-card p-5"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-blush/35"><ShieldCheck className="size-6 text-[#c66f80]" /></span><div><h2 className="font-bold">Trạng thái khóa</h2><p className="text-xs text-[#806e65]">{config.enabled ? "Đang bảo vệ trên thiết bị này" : "Chưa bật"}</p></div></div><form className="mt-5 space-y-3" onSubmit={savePin}><input className="soft-input text-center tracking-[.3em]" inputMode="numeric" type="password" maxLength={6} value={pin} onChange={(e) => setPin(e.target.value.replace(/\D/g, ""))} placeholder="PIN mới (4–6 số)" /><input className="soft-input text-center tracking-[.3em]" inputMode="numeric" type="password" maxLength={6} value={confirmPin} onChange={(e) => setConfirmPin(e.target.value.replace(/\D/g, ""))} placeholder="Nhập lại PIN" /><button className="primary-button w-full" disabled={busy}><KeyRound className="size-4" />Lưu và bật PIN</button></form><button className="secondary-button mt-3 w-full" disabled={busy} onClick={enableBiometric}><Fingerprint className="size-5" />Bật Face ID / vân tay</button>{config.enabled && <button className="mt-4 w-full text-sm font-bold text-red-700" onClick={disable}><Lock className="mr-1 inline size-4" />Tắt khóa riêng</button>}</section><p className="mt-3 text-xs text-[#806e65]">PIN và khóa sinh trắc học chỉ lưu trên thiết bị hiện tại, không được gửi lên Google Sheets.</p>{message && <p className="mt-3 rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error && <p className="mt-3 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div>;
}
